# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

w2v_train <- function(texts_, stopWords_, modelFile = "", minWordFreq = 5L, size = 100L, window = 5L, expTableSize = 1000L, expValueMax = 6L, sample = 0.001, withHS = FALSE, negative = 5L, threads = 1L, iterations = 5L, alpha = 0.05, withSG = FALSE, verbose = FALSE, normalize = TRUE) {
    .Call('_word2vec_w2v_train', PACKAGE = 'word2vec', texts_, stopWords_, modelFile, minWordFreq, size, window, expTableSize, expValueMax, sample, withHS, negative, threads, iterations, alpha, withSG, verbose, normalize)
}

w2v_load_model <- function(file, normalize = TRUE) {
    .Call('_word2vec_w2v_load_model', PACKAGE = 'word2vec', file, normalize)
}

w2v_save_model <- function(ptr, file) {
    .Call('_word2vec_w2v_save_model', PACKAGE = 'word2vec', ptr, file)
}

w2v_dictionary <- function(ptr) {
    .Call('_word2vec_w2v_dictionary', PACKAGE = 'word2vec', ptr)
}

w2v_embedding <- function(ptr, x) {
    .Call('_word2vec_w2v_embedding', PACKAGE = 'word2vec', ptr, x)
}

w2v_nearest <- function(ptr, x, top_n = 10L, min_distance = 0.0) {
    .Call('_word2vec_w2v_nearest', PACKAGE = 'word2vec', ptr, x, top_n, min_distance)
}

w2v_nearest_vector <- function(ptr, x, top_n = 10L, min_distance = 0.0) {
    .Call('_word2vec_w2v_nearest_vector', PACKAGE = 'word2vec', ptr, x, top_n, min_distance)
}

w2v_read_binary <- function(modelFile, normalize, n) {
    .Call('_word2vec_w2v_read_binary', PACKAGE = 'word2vec', modelFile, normalize, n)
}

